In [1]:
import pandas as pd

In [2]:
df_2015 = pd.read_csv('2015.csv')
df_2016 = pd.read_csv('2016.csv')
df_2017 = pd.read_csv('2017.csv')
df_2018 = pd.read_csv('2018.csv')
df_2019 = pd.read_csv('2019.csv')
df_2020 = pd.read_csv('2020.csv')

In [3]:
df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [4]:
df_2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [5]:
df_2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [6]:
df_2018.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [7]:
df_2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [8]:
df_2020.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [9]:
df_2015.rename(columns={
    'Economy (GDP per Capita)': 'GDP per capita',
    'Health (Life Expectancy)' : 'Healthy life expectancy',
    'Trust (Government Corruption)' : 'Perceptions of corruption',
    'Family':  'Social support'
}, inplace=True)

In [10]:
df_2016.rename(columns={
    'Economy (GDP per Capita)': 'GDP per capita',
    'Health (Life Expectancy)' : 'Healthy life expectancy',
    'Trust (Government Corruption)' : 'Perceptions of corruption',
    'Family':  'Social support'
}, inplace=True)

In [11]:
df_2017.rename(columns={
    'Happiness.Rank' : 'Happiness Rank',
    'Happiness.Score' : 'Happiness Score',
    'Economy..GDP.per.Capita.': 'GDP per capita',
    'Family' : 'Social support',
    'Health..Life.Expectancy.' : 'Healthy life expectancy',
    'Trust..Government.Corruption.' : 'Perceptions of corruption'
}, inplace=True)

In [12]:
df_2018.rename(columns={
    'Overall rank' : 'Happiness Rank',
    'Country or region': 'Country',
    'Score' : 'Happiness Score',
    'Freedom to make life choices': 'Freedom'
}, inplace=True)

In [13]:
df_2019.rename(columns={
    'Overall rank' : 'Happiness Rank',
    'Country or region': 'Country',
    'Score' : 'Happiness Score',
    'Freedom to make life choices': 'Freedom'
}, inplace=True)

In [14]:
df_2020.drop(['Standard error of ladder score', 'upperwhisker', 'lowerwhisker', 'Ladder score in Dystopia',
              'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
             'Freedom to make life choices', 'Generosity', 'Perceptions of corruption',
              'Dystopia + residual'], axis=1, inplace=True)

In [15]:
df_2020.head()

,Country name,Regional indicator,Ladder score,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [16]:
df_2020.rename(columns={
    'Country name': 'Country',
    'Regional indicator': 'region',
    'Ladder score' : 'Happiness Score',
    'Explained by: Log GDP per capita': 'GDP per capita',
    'Explained by: Freedom to make life choices' : 'Freedom',
    'Explained by: Social support' : 'Social support',
    'Explained by: Healthy life expectancy': 'Healthy life expectancy',
    'Explained by: Generosity' : 'Generosity',
    'Explained by: Perceptions of corruption' : 'Perceptions of corruption'
}, inplace=True)

In [17]:
df_2020.head()

,Country,region,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Generosity,Perceptions of corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [18]:
df_2015.drop(['Standard Error', 'Dystopia Residual'], 1, inplace=True)

In [19]:
df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811

In [20]:
df_2016.drop(['Lower Confidence Interval', 'Upper Confidence Interval', 'Dystopia Residual'], 1, inplace=True)

In [21]:
df_2017.drop(['Whisker.high', 'Whisker.low', 'Dystopia.Residual'], 1, inplace=True)

In [22]:
df_2020.tail()

,Country,region,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Generosity,Perceptions of corruption
148,Central African Republic,Sub-Saharan Africa,3.4759,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265
149,Rwanda,Sub-Saharan Africa,3.3123,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929
151,South Sudan,Sub-Saharan Africa,2.8166,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157
152,Afghanistan,South Asia,2.5669,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226

In [23]:
rank = [i for i in range(1, len(df_2020['Country']) + 1)]
df_2020['Happiness Rank'] = rank

In [25]:
df_2020.tail()

,Country,region,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Generosity,Perceptions of corruption,Happiness Rank
148,Central African Republic,Sub-Saharan Africa,3.4759,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,149
149,Rwanda,Sub-Saharan Africa,3.3123,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,150
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,151
151,South Sudan,Sub-Saharan Africa,2.8166,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,152
152,Afghanistan,South Asia,2.5669,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,153

In [26]:
country = pd.concat([df_2015['Country'], df_2015['Region']], axis=1)

In [27]:
country.head()

       Country          Region
0  Switzerland  Western Europe
1      Iceland  Western Europe
2      Denmark  Western Europe
3       Norway  Western Europe
4       Canada   North America

In [28]:
country.rename(index=country['Country'], inplace=True)

In [29]:
country.drop('Country', 1, inplace=True)

In [30]:
country.head()

                     Region
Switzerland  Western Europe
Iceland      Western Europe
Denmark      Western Europe
Norway       Western Europe
Canada        North America

In [31]:
country_dict = country.to_dict()

In [32]:
country_dict['Region']

{'Switzerland': 'Western Europe',
 'Iceland': 'Western Europe',
 'Denmark': 'Western Europe',
 'Norway': 'Western Europe',
 'Canada': 'North America',
 'Finland': 'Western Europe',
 'Netherlands': 'Western Europe',
 'Sweden': 'Western Europe',
 'New Zealand': 'Australia and New Zealand',
 'Australia': 'Australia and New Zealand',
 'Israel': 'Middle East and Northern Africa',
 'Costa Rica': 'Latin America and Caribbean',
 'Austria': 'Western Europe',
 'Mexico': 'Latin America and Caribbean',
 'United States': 'North America',
 'Brazil': 'Latin America and Caribbean',
 'Luxembourg': 'Western Europe',
 'Ireland': 'Western Europe',
 'Belgium': 'Western Europe',
 'United Arab Emirates': 'Middle East and Northern Africa',
 'United Kingdom': 'Western Europe',
 'Oman': 'Middle East and Northern Africa',
 'Venezuela': 'Latin America and Caribbean',
 'Singapore': 'Southeastern Asia',
 'Panama': 'Latin America and Caribbean',
 'Germany': 'Western Europe',
 'Chile': 'Latin America and Caribbean',
 'Qatar': 'Middle East and Northern Africa',
 'France': 'Western Europe',
 'Argentina': 'Latin America and Caribbean',
 'Czech Republic': 'Central and Eastern Europe',
 'Uruguay': 'Latin America and Caribbean',
 'Colombia': 'Latin America and Caribbean',
 'Thailand': 'Southeastern Asia',
 'Saudi Arabia': 'Middle East and Northern Africa',
 'Spain': 'Western Europe',
 'Malta': 'Western Europe',
 'Taiwan': 'Eastern Asia',
 'Kuwait': 'Middle East and Northern Africa',
 'Suriname': 'Latin America and Caribbean',
 'Trinidad and Tobago': 'Latin America and Caribbean',
 'El Salvador': 'Latin America and Caribbean',
 'Guatemala': 'Latin America and Caribbean',
 'Uzbekistan': 'Central and Eastern Europe',
 'Slovakia': 'Central and Eastern Europe',
 'Japan': 'Eastern Asia',
 'South Korea': 'Eastern Asia',
 'Ecuador': 'Latin America and Caribbean',
 'Bahrain': 'Middle East and Northern Africa',
 'Italy': 'Western Europe',
 'Bolivia': 'Latin America and Caribbean',
 'Moldova': 'Central and Eastern Europe',
 'Paraguay': 'Latin America and Caribbean',
 'Kazakhstan': 'Central and Eastern Europe',
 'Slovenia': 'Central and Eastern Europe',
 'Lithuania': 'Central and Eastern Europe',
 'Nicaragua': 'Latin America and Caribbean',
 'Peru': 'Latin America and Caribbean',
 'Belarus': 'Central and Eastern Europe',
 'Poland': 'Central and Eastern Europe',
 'Malaysia': 'Southeastern Asia',
 'Croatia': 'Central and Eastern Europe',
 'Libya': 'Middle East and Northern Africa',
 'Russia': 'Central and Eastern Europe',
 'Jamaica': 'Latin America and Caribbean',
 'North Cyprus': 'Western Europe',
 'Cyprus': 'Western Europe',
 'Algeria': 'Middle East and Northern Africa',
 'Kosovo': 'Central and Eastern Europe',
 'Turkmenistan': 'Central and Eastern Europe',
 'Mauritius': 'Sub-Saharan Africa',
 'Hong Kong': 'Eastern Asia',
 'Estonia': 'Central and Eastern Europe',
 'Indonesia': 'Southeastern Asia',
 'Vietnam': 'Southeastern Asia',
 'Turkey': 'Middle East and Northern Africa',
 'Kyrgyzstan': 'Central and Eastern Europe',
 'Nigeria': 'Sub-Saharan Africa',
 'Bhutan': 'Southern Asia',
 'Azerbaijan': 'Central and Eastern Europe',
 'Pakistan': 'Southern Asia',
 'Jordan': 'Middle East and Northern Africa',
 'Montenegro': 'Central and Eastern Europe',
 'China': 'Eastern Asia',
 'Zambia': 'Sub-Saharan Africa',
 'Romania': 'Central and Eastern Europe',
 'Serbia': 'Central and Eastern Europe',
 'Portugal': 'Western Europe',
 'Latvia': 'Central and Eastern Europe',
 'Philippines': 'Southeastern Asia',
 'Somaliland region': 'Sub-Saharan Africa',
 'Morocco': 'Middle East and Northern Africa',
 'Macedonia': 'Central and Eastern Europe',
 'Mozambique': 'Sub-Saharan Africa',
 'Albania': 'Central and Eastern Europe',
 'Bosnia and Herzegovina': 'Central and Eastern Europe',
 'Lesotho': 'Sub-Saharan Africa',
 'Dominican Republic': 'Latin America and Caribbean',
 'Laos': 'Southeastern Asia',
 'Mongolia': 'Eastern Asia',
 'Swaziland': 'Sub-Saharan Africa',
 'Greece': 'Western Europe',
 'Lebanon': 'Middle East and Northern Africa',
 'Hungary': 'Central and Eastern Europe',
 'Honduras': 'Latin America and Caribbean',
 'Tajikistan': 'Central and Eastern Europe',
 'Tunisia': 'Middle East and Northern Africa',
 'Palestinian Territories': 'Middle East and Northern Africa',
 'Bangladesh': 'Southern Asia',
 'Iran': 'Middle East and Northern Africa',
 'Ukraine': 'Central and Eastern Europe',
 'Iraq': 'Middle East and Northern Africa',
 'South Africa': 'Sub-Saharan Africa',
 'Ghana': 'Sub-Saharan Africa',
 'Zimbabwe': 'Sub-Saharan Africa',
 'Liberia': 'Sub-Saharan Africa',
 'India': 'Southern Asia',
 'Sudan': 'Sub-Saharan Africa',
 'Haiti': 'Latin America and Caribbean',
 'Congo (Kinshasa)': 'Sub-Saharan Africa',
 'Nepal': 'Southern Asia',
 'Ethiopia': 'Sub-Saharan Africa',
 'Sierra Leone': 'Sub-Saharan Africa',
 'Mauritania': 'Sub-Saharan Africa',
 'Kenya': 'Sub-Saharan Africa',
 'Djibouti': 'Sub-Saharan Africa',
 'Armenia': 'Central and Eastern Europe',
 'Botswana': 'Sub-Saharan Africa',
 'Myanmar': 'Southeastern Asia',
 'Georgia': 'Central and Eastern Europe',
 'Malawi': 'Sub-Saharan Africa',
 'Sri Lanka': 'Southern Asia',
 'Cameroon': 'Sub-Saharan Africa',
 'Bulgaria': 'Central and Eastern Europe',
 'Egypt': 'Middle East and Northern Africa',
 'Yemen': 'Middle East and Northern Africa',
 'Angola': 'Sub-Saharan Africa',
 'Mali': 'Sub-Saharan Africa',
 'Congo (Brazzaville)': 'Sub-Saharan Africa',
 'Comoros': 'Sub-Saharan Africa',
 'Uganda': 'Sub-Saharan Africa',
 'Senegal': 'Sub-Saharan Africa',
 'Gabon': 'Sub-Saharan Africa',
 'Niger': 'Sub-Saharan Africa',
 'Cambodia': 'Southeastern Asia',
 'Tanzania': 'Sub-Saharan Africa',
 'Madagascar': 'Sub-Saharan Africa',
 'Central African Republic': 'Sub-Saharan Africa',
 'Chad': 'Sub-Saharan Africa',
 'Guinea': 'Sub-Saharan Africa',
 'Ivory Coast': 'Sub-Saharan Africa',
 'Burkina Faso': 'Sub-Saharan Africa',
 'Afghanistan': 'Southern Asia',
 'Rwanda': 'Sub-Saharan Africa',
 'Benin': 'Sub-Saharan Africa',
 'Syria': 'Middle East and Northern Africa',
 'Burundi': 'Sub-Saharan Africa',
 'Togo': 'Sub-Saharan Africa'}

In [33]:
df_2017['Region'] = df_2017['Country'].map(country_dict['Region'])

In [34]:
df_2018['Region'] = df_2018['Country'].map(country_dict['Region'])

In [35]:
df_2019['Region'] = df_2019['Country'].map(country_dict['Region'])

In [36]:
df_2020['Region'] = df_2020['Country'].map(country_dict['Region'])
df_2020.drop('region', axis=1, inplace=True)

In [37]:
df_2017.dropna(inplace=True)
df_2018.dropna(inplace=True)
df_2019.dropna(inplace=True)
df_2020.dropna(inplace=True)

In [38]:
df_2015['Year'] = 2015
df_2016['Year'] = 2016
df_2017['Year'] = 2017
df_2018['Year'] = 2018
df_2019['Year'] = 2019
df_2020['Year'] = 2020

In [39]:
df = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019, df_2020], axis=0, ignore_index=True)

In [40]:
df.head()

,Country,Region,Happiness Rank,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity,Year
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

In [41]:
df.to_csv('countries_happiness_data.csv', index=False)

In [1]:
import pandas as pd

df = pd.read_csv('countries_happiness_data.csv')

df.head()

,Country,Region,Happiness Rank,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity,Year
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

In [14]:
df_year = df.groupby(['Year'], as_index=False).mean()

In [15]:
df_year.head()

,Year,Happiness Rank,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity
0,2015,79.493671,5.375734,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296
1,2016,78.980892,5.382185,0.953880,0.793621,0.557619,0.370994,0.137624,0.242635
2,2017,77.410596,5.368219,0.995623,1.197197,0.558884,0.407582,0.122481,0.247500
3,2018,78.590604,5.377242,0.889262,1.222040,0.603436,0.454034,0.111718,0.181242
4,2019,77.570470,5.433872,0.914315,1.214946,0.732060,0.393544,0.110456,0.184503

In [16]:
df_year.drop('Happiness Rank', 1, inplace=True)

In [17]:
df_year

,Year,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity
0,2015,5.375734,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296
1,2016,5.382185,0.953880,0.793621,0.557619,0.370994,0.137624,0.242635
2,2017,5.368219,0.995623,1.197197,0.558884,0.407582,0.122481,0.247500
3,2018,5.377242,0.889262,1.222040,0.603436,0.454034,0.111718,0.181242
4,2019,5.433872,0.914315,1.214946,0.732060,0.393544,0.110456,0.184503
5,2020,5.497306,0.870025,1.157296,0.694629,0.466378,0.130206,0.187748

In [18]:
df_year.to_csv('year_wise_mean.csv', index=False)

In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
from dash.dependencies import Input, Output
from plotly.subplots import make_subplots
import pandas as pd
import plotly.express as px
import numpy as np
from sklearn.linear_model import LinearRegression
import base64

In [2]:
df = pd.read_csv('countries_happiness_data.csv')
df_year = pd.read_csv('year_wise_mean.csv')

app = dash.Dash(__name__)

image_filename = 'mitti_ke_rang_logo.jpeg'
encoded_image = base64.b64encode(open(image_filename, 'rb').read())


app.layout = html.Div([
    html.H1('WORLD OF HAPPINESS', style={'text-align': 'center',
                                        'display': 'inline-block',
                                        'font-size': '3em',
                                         'width': '100%',
                                         'text-align': 'center',
                                        'background-color': '#52D991',
                                        'font-weight': 'bold',
                                        'color': '#C60012'}),

    html.Img(src='data:image/jpeg;base64,{}'.format(encoded_image.decode()),
             height=80, width=80, style={'display': 'block', 'margin-left': 'auto', 'margin-right': 'auto',
                                         'background-color': '#52D991'}),
    
    dcc.Dropdown(id='select-year',
                 options = [
                     {'label': '2015', 'value': 2015},
                     {'label': '2016', 'value': 2016},
                     {'label': '2017', 'value': 2017},
                     {'label': '2018', 'value': 2018},
                     {'label': '2019', 'value': 2019},
                     {'label': '2020', 'value': 2020}],
                value=2015,                                                                                               
                style={'width':"40%", 'font-size': 20}),
    
    html.Div(id='output-container', children=[], style={'font-size': 30, 'left': '200%', 'text-align': 'center'}),
    html.Br(),
    
    dcc.Graph(id='country-map', figure={})
    
])

@app.callback(
        [Output(component_id='output-container', component_property='children'),
        Output(component_id='country-map', component_property='figure')],
        [Input(component_id='select-year', component_property='value')]
)

def update_graph(option_selected):
    
    container = "Year : {}".format(option_selected)
    
    dff = df.copy()
    dff = dff[dff['Year'] == option_selected]
    
    fig = make_subplots(
        rows=5, cols=2,
        vertical_spacing = 0.1,
        specs=[[{"type": "choropleth", 'rowspan': 2}, {"type": "scatter"}],
               [       None           , {"type": "box"}],
               [{'type': 'bar', 'colspan': 2},    None ],
               [{"type": 'scatter'},  {'type': 'scatter'}],
               [{"type": 'scatter'},  {'type': 'scatter'}]],
        subplot_titles=('HAPPINESS SCORE OF COUNTRIES',
                        'YEAR WISE VARIATIONS IN HAPPINESS FACTORS',
                        'REGION WISE FREEDOM',
                        'TOP 20 HAPPIEST COUNTRIES',
                        'HAPPINESS SCORE V/S GDP PER CAPITA',
                        'HAPPINESS SCORE V/S SOCIAL SUPPORT',
                        'HAPPINESS SCORE V/S HEALTHY LIFE EXPECTANCY',
                        'HAPPINESS SCORE V/S FREEDOM',
                       ))

    fig.add_trace(
        go.Choropleth(
            locationmode = 'country names',
            locations = dff['Country'],
            z = dff['Happiness Score'],
            colorscale='Reds',
            name = 'Happiness Score',
            showlegend=False,
            showscale=False,
            text = dff['Happiness Rank'],
            hoverlabel = dict(bgcolor='black',
                             font=dict(size=18))
            ),
        row=1, col=1
    )
    
    fig.update_geos(
        projection_type='miller',
        oceancolor="#65A9C1",
        showocean=True
    )
    
    fig.add_trace(
        go.Scatter(x=df_year['Year'], y=df_year['GDP per capita'], mode='lines+markers', name='GDP per capita'),
        row=1, col=2
    )
    
    fig.add_trace(
         go.Scatter(x=df_year['Year'], y=df_year['Social support'], mode='lines+markers', name='Social support'),
        row=1, col=2
    )
    
    fig.add_trace(
         go.Scatter(x=df_year['Year'], y=df_year['Healthy life expectancy'], mode='lines+markers', name='Healthy life expectancy'),
        row=1, col=2
    )
    
    fig.add_trace(
         go.Scatter(x=df_year['Year'], y=df_year['Freedom'], mode='lines+markers', name='Freedom'),
        row=1, col=2
    )
    
    fig.add_trace(
         go.Scatter(x=df_year['Year'], y=df_year['Perceptions of corruption'], mode='lines+markers',
                    name='Perception of Corruption'),
        row=1, col=2
    )
    
    fig.add_trace(
         go.Scatter(x=df_year['Year'], y=df_year['Generosity'], mode='lines+markers', name='Generosity'),
        row=1, col=2
    )
    
    
    fig.add_trace(
        go.Box(x=dff['Region'], y=dff['Freedom'],
               marker=dict(color='crimson'), showlegend=False, xaxis='x2', yaxis='y2'),
        row=2, col=2
    )
    
    fig.update_layout(xaxis = dict(domain=[0.55, 1]),
                     yaxis = dict(domain=[0.83, 0.99]))
    
    fig.add_trace(go.Bar(x=dff['Country'][:20],
                         y=dff['Happiness Score'][:20],
                         text = dff['Happiness Rank'],
                         showlegend=False,
                        marker=dict(color='crimson'),
                        name = 'Happiness'),
                 row = 3, col = 1)
    
    
    X1 = dff['GDP per capita'].values.reshape(-1, 1)
    X2 = dff['Social support'].values.reshape(-1, 1)
    X3 = dff['Healthy life expectancy'].values.reshape(-1, 1)
    X4 = dff['Freedom'].values.reshape(-1, 1)
    y = dff['Happiness Score']
    
    model1 = LinearRegression()
    model2 = LinearRegression()
    model3 = LinearRegression()
    model4 = LinearRegression()
 
    model1.fit(X1, y)
    model2.fit(X2, y)
    model3.fit(X3, y)
    model4.fit(X4, y)
    
    x_range1 = np.linspace(X1.min(), X1.max(), 100)
    y_range1 = model1.predict(x_range1.reshape(-1, 1))
    
    x_range2 = np.linspace(X2.min(), X2.max(), 100)
    y_range2 = model2.predict(x_range2.reshape(-1, 1))
    
    x_range3 = np.linspace(X3.min(), X3.max(), 100)
    y_range3 = model3.predict(x_range3.reshape(-1, 1))
    
    x_range4 = np.linspace(X4.min(), X4.max(), 100)
    y_range4 = model4.predict(x_range4.reshape(-1, 1))


    fig.add_trace(go.Scatter(x=dff['GDP per capita'],
                             y=dff['Happiness Score'],
                             mode='markers',
                             showlegend=False,
                             name='GDP per capita',
                             marker=dict(color='red', size=10),
                             xaxis='x3', yaxis='y3'),
                  row = 4, col = 1
                 )
    fig.add_trace(go.Scatter(x=x_range1, y=y_range1, marker=dict(color='black'), showlegend=False,
                             line=dict(dash='dash')), row=4, col=1)

    fig.add_trace(go.Scatter(x=dff['Social support'],
                             y=dff['Happiness Score'],
                             mode='markers',
                             showlegend=False,
                             name='Social Support',
                             marker=dict(color='blue', size=10),
                            xaxis='x4', yaxis='y4'),
                  row = 4, col = 2
                 )
    fig.add_trace(go.Scatter(x=x_range2, y=y_range2, marker=dict(color='black'), showlegend=False,
                            line=dict(dash='dash')), row=4, col=2)
    
    fig.add_trace(go.Scatter(x=dff['Healthy life expectancy'],
                             y=dff['Happiness Score'],
                             mode='markers',
                             showlegend=False,
                             name='Healthy life expectancy',
                             marker=dict(color='green', size=10)),
                  row = 5, col = 1
                 )
    fig.add_trace(go.Scatter(x=x_range3, y=y_range3, marker=dict(color='black'), showlegend=False,
                            line=dict(dash='dash')), row=5, col=1)
    
    fig.add_trace(go.Scatter(x=dff['Freedom'],
                             y=dff['Happiness Score'],
                             mode='markers',
                             showlegend=False,
                             name='Freedom',
                             marker=dict(color='brown', size=10)),
                  row = 5, col = 2
                 )
    fig.add_trace(go.Scatter(x=x_range4, y=y_range4, marker=dict(color='black'), showlegend=False,
                            line=dict(dash='dash')), row=5, col=2)
    
    
    fig.update_xaxes(title_text='Country', row=3, col=1)
    fig.update_xaxes(title_text='GDP per Capita', row=4, col=1)
    fig.update_xaxes(title_text='Social Support', row=4, col=2)
    fig.update_xaxes(title_text='Healthy Life Expectancy', row=5, col=1)
    fig.update_xaxes(title_text='Freedom', row=5, col=2)
    
    
    fig.update_yaxes(title_text='Happiness Score', row=3, col=1)
    fig.update_yaxes(title_text='Happiness Score', row=4, col=1)
    fig.update_yaxes(title_text='Happiness Score', row=4, col=2)
    fig.update_yaxes(title_text='Happiness Score', row=5, col=1)
    fig.update_yaxes(title_text='Happiness Score', row=5, col=2)
    
    
    fig.update_xaxes(title_text = 'Year', row=1, col=2)
    #fig.update_xaxes(title_text = 'Region', row=2, col=2)
    
    fig.update_yaxes(title_text = 'Avg. Values', row=1, col=2)
    fig.update_yaxes(title_text = 'Freedom', row=2, col=2)
    
    for i in fig['layout']['annotations']:
        i['font'] = dict(size=22, color='#C60012')
        
    
    fig.update_layout(
        hoverlabel = dict(font=dict(size=18),
                         bgcolor='black'),
        height = 1800,
        title_font_size = 30,
        margin=dict(r=10, t=30, b=10, l=10),
        font_size = 15
    )
    
    return container, fig

if __name__ == '__main__':
    app.run_server()

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Jan/2021 20:23:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 20:23:09] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 20:23:09] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [07/Jan/2021 20:23:22] "POST /_dash-update-component HTTP/1.1" 200 -